[package]
name = "perp-api"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
axum.workspace = true
bigdecimal.workspace = true
chrono.workspace = true
clap.workspace = true
diesel = { workspace = true, features = ["postgres", "serde_json", "numeric"] }
diesel-async = { workspace = true, features = ["bb8", "postgres"] }
futures-util.workspace = true
num-bigint.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true

haneul-indexer-alt-metrics.workspace = true
haneul-pg-db.workspace = true
telemetry-subscribers.workspace = true

perp-engine.workspace = true

[[bin]]
name = "perp-api"
path = "src/main.rs"
